### ISSUE TITLE
Failed to load a language-naniscript package grammar

### ISSUE THREAD

**Issue by ssorasora** [Elringus/NaninovelAtom#2]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.41.0 x64
**Electron**: 4.2.7
**OS**: Unknown Windows version
**Thrown From**: [language-naniscript](https://github.com/Elringus/NaninovelAtom) package 0.41.0

### Stack Trace

Failed to load a language-naniscript package grammar

```
At The specified module could not be found.
\\?\C:\Users\max\.atom\packages\language-naniscript\node_modules\tree-sitter-naninovel\build\Release\tree_sitter_naniscript_binding.node in C:\Users\max\.atom\packages\language-naniscript\grammars\naniscript.cson

Error: The specified module could not be found.
\\?\C:\Users\max\.atom\packages\language-naniscript\node_modules\tree-sitter-naninovel\build\Release\tree_sitter_naniscript_binding.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:160:31)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:146745)
    at /packages/language-naniscript/node_modules/tree-sitter-naninovel/index.js:2:20)
    at /packages/language-naniscript/node_modules/tree-sitter-naninovel/index.js:15:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:1:727373)
    at new TreeSitterGrammar (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:3235890)
    at GrammarRegistry.createGrammar (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:360047)
    at l.readFile (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:359888)
    at ~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:581849
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
  at /packages/language-naniscript/grammars/naniscript.cson:1:1
```

### Commands

```
```

### Non-Core Packages

```
atom-i18n 0.21.1 
atom-ide-ui 0.13.0 
language-naniscript 0.41.0 
linter 2.3.1 
linter-spell 0.15.0 
```

**Comment by Elringus** [comment]
Hi, Thanks for the report! Try removing the extension, then manually delete `C:\Users\max\.atom\packages\language-naniscript` (if it's still there after the removal) and install the extension again. Also, make sure to follow all the installation and usage steps mentioned in the readme.

**Comment by JohnnyMonty** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.52.0 x64
**Electron**: 6.1.12
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [language-naniscript](https://github.com/Elringus/NaninovelAtom) package 0.53.0


### Stack Trace

Failed to load a language-naniscript package grammar

```
At Cannot find module './build/Release/tree_sitter_naniscript_binding'
Require stack:
- C:\Users\Johnny\.atom\packages\language-naniscript\node_modules\tree-sitter-naninovel\index.js
- C:\Users\Johnny\AppData\Local\atom\app-1.52.0\resources\app.asar\static\index.html in C:\Users\Johnny\.atom\packages\language-naniscript\grammars\naniscript.cson

Error: Cannot find module './build/Release/tree_sitter_naniscript_binding'
Require stack:
- C:\Users\Johnny\.atom\packages\language-naniscript\node_modules\tree-sitter-naninovel\index.js
- C:\Users\Johnny\AppData\Local\atom\app-1.52.0\resources\app.asar\static\index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:627:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.52.0/resources/electron.asar/common/reset-search-paths.js:41:16)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:11:155481)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:11:146814)
    at /packages/language-naniscript/node_modules/tree-sitter-naninovel/index.js:2:20)
    at /packages/language-naniscript/node_modules/tree-sitter-naninovel/index.js:15:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:16:16)
    at customRequire (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:1:735077)
    at new TreeSitterGrammar (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:11:3214192)
    at GrammarRegistry.createGrammar (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:11:360618)
    at ~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:11:360459
    at ~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:11:582485
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3)
  at /packages/language-naniscript/grammars/naniscript.cson:1:1
```

### Commands

```
```

### Non-Core Packages

```
atom-ide-ui 0.13.0 
language-naniscript 0.53.0 
```

**Comment by Elringus** [comment]
Hey, The Atom extension is deprecated as Atom itself is no longer actively developed/supported. Please VS Code extension instead: https://naninovel.com/guide/ide-extension.html
